CREATE TABLE IF NOT EXISTS "user" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "username" varchar(20),
    "password" varchar(250),
    "first_name" varchar(25),
    "last_name" varchar(25),
    "email" varchar(25),
    CONSTRAINT "user_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "role" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "name" varchar(25),
    CONSTRAINT "role_pkey" PRIMARY KEY (id)
);