CREATE TABLE IF NOT EXISTS "delivery_address" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "user_id" bigint,
    "address" varchar(250),
    CONSTRAINT "delivery_address_pkey" PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES winter_market.user
);